services:
  - type: web
    name: via-english-academy-fullstack
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://via-english-academy-fullstack.onrender.com"
      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      # Gmail Service
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      # Cloudinary Service
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Gemini AI
      - key: GEMINI_API_KEY
        sync: false
      # Optional Legacy Keys (if needed)
      - key: OPENAI_API_KEY
        sync: false
      - key: OBJECT_STORAGE_BUCKET
        sync: false
      - key: OBJECT_STORAGE_KEY_ID
        sync: false
      - key: OBJECT_STORAGE_SECRET
        sync: false
    healthCheckPath: /api/health
    domains:
      - via-english-academy-fullstack.onrender.com
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: via-academy-disk
      size: 1GB
      mount: /tmp