services:
  - type: web
    name: via-english-academy-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: OBJECT_STORAGE_BUCKET
        sync: false
      - key: OBJECT_STORAGE_KEY_ID
        sync: false
      - key: OBJECT_STORAGE_SECRET
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_ID
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_DRIVE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://your-frontend-domain.vercel.app"
    healthCheckPath: /api/health
    domains:
      - via-english-academy-api.onrender.com
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: via-academy-disk
      size: 1GB
      mount: /tmp